services:
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://server:5000

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=Comments
      - ADMIN_USER=admin
      - ADMIN_PASS=Admin123.
      - ADMIN_EMAIL=admin@gmail.com
      - PORT=5000
    volumes:
      - server-env:/app/.env

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  server-env:
